version: '3'

services:
  recorder:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCREAM_BOOTH_RECORDER_OUT_DIR=/recordings/out
      - SCREAM_BOOTH_RECORDER_OUT_TMP_DIR=/recordings/tmp
      - SCREAM_BOOTH_CONTROLLER_PORT=${SCREAM_BOOTH_CONTROLLER_PORT}
      - SCREAM_BOOTH_CONTROLLER_PORT_SPEED=57600
      - "DEBUG=scream-booth:*"
#      - SOX_AUDIODEV=hw:CARD=Intel,DEV=0
#      - SOX_AUDIODRIVER=alsa
    devices:
      - "${DOCKER_HOST_SCREAM_BOOTH_CONTROLLER_PORT}:${SCREAM_BOOTH_CONTROLLER_PORT}"
      - "/dev/snd/controlC0:/dev/snd/controlC0"
      - "/dev/snd/pcmC0D0c:/dev/snd/pcmC0D0c"
      - "/dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p"
      - "/dev/snd/pcmC0D3p:/dev/snd/pcmC0D3p"
      - "/dev/snd/pcmC0D1c:/dev/snd/pcmC0D1c"
      - "/dev/snd/hwC0D0:/dev/snd/hwC0D0"
      - "/dev/snd/hwC0D2:/dev/snd/hwC0D2"
      - "/dev/snd/seq:/dev/snd/seq"
      - "/dev/snd/timer:/dev/snd/timer"
    volumes:
      - "scream-booth-recordings:/recordings:rw"
    restart: unless-stopped

  uploader:
    build:
      context: .
      dockerfile: uploader/Dockerfile
    extra_hosts:
      - "scream-booth-upload-server:${SCREAM_BOOTH_UPLOAD_SERVER_IP}"
    environment:
      - UPLOAD_SOURCE_DIR=/recordings/out
      - UPLOAD_DEST=${SCREAM_BOOTH_UPLOADER_USER}@scream-booth-upload-server:/recorder_uploads
    volumes:
      - "scream-booth-recordings:/recordings:rw"
      - "./uploader/id_rsa:/ssh/id_rsa:ro"

volumes:
  scream-booth-recordings:
    external: true