version: '3'

services:
  recorder:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SCREAM_BOX_RECORDER_OUT_DIR=/recordings
      - SCREAM_BOX_CONTROLLER_PORT=${SCREAM_BOX_CONTROLLER_PORT}
      - SCREAM_BOX_CONTROLLER_PORT_SPEED=57600
      - "DEBUG=scream-booth:*"
      - SOX_AUDIODEV=hw:CARD=I82801AAICH,DEV=0
      - SOX_AUDIODRIVER=alsa
    devices:
      - "${DOCKER_HOST_SCREAM_BOX_CONTROLLER_PORT}:${SCREAM_BOX_CONTROLLER_PORT}"
      - "/dev/snd/controlC0:/dev/snd/controlC0"
      - "/dev/snd/pcmC0D0c:/dev/snd/pcmC0D0c"
      - "/dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p"
      - "/dev/snd/pcmC0D1c:/dev/snd/pcmC0D1c"
      - "/dev/snd/seq:/dev/snd/seq"
      - "/dev/snd/timer:/dev/snd/timer"
    volumes:
      - "./recordings:/recordings:rw"

volumes:
  scream-recordings: